---
- name: deploying Spring Boot Web Application
  hosts: all
  vars_files:
    - /opt/docker/deploy-using-ansible/secret
  vars:
    image_version: "{{ ver }}"
  # Doesn't need root access to create an image
  #become: true 

  tasks:
  - name: build docker image
    command: docker build -t spring-boot-webapp .
    args:
      chdir: /opt/docker/deploy-using-ansible

  - name: create tag to image
    command: docker tag spring-boot-webapp {{ ecr }}/spring-boot-webapp

  # https://stackoverflow.com/questions/58695853/docker-image-tagging-in-ecr
  - name: push image on to ECR (will become the ":latest")
    command: docker push {{ ecr }}/spring-boot-webapp

  - name: create tag to image (with version info)
    command: docker tag spring-boot-webapp {{ ecr }}/spring-boot-webapp:{{ ver }}

  - name: push image on to ECR
    command: docker push {{ ecr }}/spring-boot-webapp:{{ ver }}
