---
- name: deploying Spring Boot Web Application
  hosts: all
  # Doesn't need root access to create an image
  #become: true 

  tasks:
  - name: stop current running spring-boot-webapp-container
    command: docker stop spring-boot-webapp-container
    ignore_errors: yes

  - name: remove stopped container 
    command: docker rm spring-boot-webapp-container
    ignore_errors: yes

  - name: remove docker image
    command: docker rmi spring-boot-webapp
    ignore_errors: yes

  - name: build docker image
    command: docker build -t spring-boot-webapp .
    args:
      chdir: /opt/docker
  
  - name: create docker image using docker command
    command: docker run -d --name spring-boot-webapp-container -p 8080:8080 spring-boot-webapp